config/routes.rb
Rails.application.routes.draw do
  resources :setors
  resources :departamentos
  #Ele vai buscar em produtos a url busca, no controller produtos e usar o método busca
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos, only: [:new, :destroy, :create, :edit, :update]
  root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
    #Um produto pertence a setor
    belongs_to :setor, optional: true


    validates :preco, presence: true
    validates :nome, presence: true, length: { minimum: 3}
    #Se a descrição possui uma quantidade entre 5 caracteres e 200
    validates :descricao, presence: true, length: { in: 5..200}
    validates :quantidade, presence: true, length: { minimum: 1 }
    
    #Exemplos de validações

    # Se o campo cpf possui 11 caracteres
    # validates :cpf, length: { is: 11 }

    # Se o campo numero é um valor numérico do tipo inteiro
    # validates :numero, numericality: { only_integer: true }
end

app/models/setor.rb
class Setor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
    @produtos_por_setor = Produto.where("departamento_id = ?", params[:id])
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.fetch(:departamento, {})
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    #Antes de qualquer função ex:. edit, update... Ele irá executar a função set_produto que irá buscar os parametros do arquivo
    before_action :set_produto, only: [:edit, :update, :destroy]

    def index
        #Ordenar os produtos por ordem alfabética com um limite de 6 produtos por página
        @produtos = Produto.order(nome: :asc).limit 6

        #Ordenaros por preço, busca o menor preço e limita a apenas aparecer ele
        @produto_menor_preco = Produto.order(:preco).limit 1
    end

    #Função que sempre que entrar na página irá setar um novo produto
    def new
        #Instancia o produto como uma variavel global
        @produto = Produto.new
        @setores = Setor.all  #Para exibir os setores no select
    end

    def create
        #Recebe os dados do novo arquivo e insere na variavel 'produto'
        #Cria um novo produto com os dados do arquivo e salva no banco de dados
        @produto = Produto.new produto_params
        if @produto.save
            #Se salvar com sucesso, renderiza uma mensagem de sucesso
            flash[:notice] = "Produto salvo com sucesso!"
            #Redireciona para a página de produtos
            redirect_to root_url
        else
            #Redireciona novamente para a página de criação de produtos
            renderize :new
        end
    end

    def busca
        #Instancia o nome como uma variavel global, e recebe os parametros de nome
        @nome = params[:nome]
        #Adicionando as porcentagens para que o nome seja buscado como parte do nome
            #Instancia o produtos como uma variavel global e passa a Query where com o nome
            #"nome like?" para indicar que o nome deve ser buscado como parte do nome e evitar SQL Injection
        @produtos = Produto.where "nome like ?", "%#{@nome}%"
    end

    def edit
        #Após receber os parametros do produto no before_action com a função set_produto, ele faz a ediçã
        renderize :edit
    end

    def update
        if @produto.update produto_params
            flash[:notice] = "Produto atualizado com sucesso!"
            redirect_to root_url
        else
            renderize :edit
        end
    end

    def destroy
        #Após receber os parametros do produto no before_action com a função set_produto, ele faz a exclusão
        @produto.destroy
        redirect_to root_url
    end

    private
    #Função que recebe os parametros do arquivo e retorna um hash
    def produto_params
        #Recebe os parametros do arquivo
        params.require(:produto).permit(:nome, :descricao,:preco,:quantidade, :setor_id)
    end

    #Função que seta os parametros do arquivo
    def set_produto
        id = params[:id]
        # @produto recebe os dados do produto com o id passado
        @produto = Produto.find(params[:id])
    end


    #Função que renderiza a página de criação de produtos
    def renderize(view)
        @setores = Setor.all
        render view
    end

end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
  before_action :set_setor, only: %i[ show edit update destroy ]

  # GET /setors or /setors.json
  def index
    @setors = Setor.all
  end

  # GET /setors/1 or /setors/1.json
  def show
    @produtos_por_setor = Produto.where("setor_id = ?", params[:id])
  end

  # GET /setors/new
  def new
    @setor = Setor.new
  end

  # GET /setors/1/edit
  def edit
  end

  # POST /setors or /setors.json
  def create
    @setor = Setor.new(setor_params)

    respond_to do |format|
      if @setor.save
        format.html { redirect_to setor_url(@setor), notice: "Setor was successfully created." }
        format.json { render :show, status: :created, location: @setor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setors/1 or /setors/1.json
  def update
    respond_to do |format|
      if @setor.update(setor_params)
        format.html { redirect_to setor_url(@setor), notice: "Setor was successfully updated." }
        format.json { render :show, status: :ok, location: @setor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1 or /setors/1.json
  def destroy
    @setor.destroy

    respond_to do |format|
      format.html { redirect_to setors_url, notice: "Setor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setor
      @setor = Setor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setor_params
      params.require(:setor).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/departamentos/_form.html.erb
<%= form_for(departamento) do |f| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= link_to 'Produtos', departamento %></td>
        <td><%= link_to 'Editar', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Deletar', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
          <%# Quando não temos um objeto vinculado a por exemplo text_field, que em um formulário seria
          form.text_field, adicionamos tag no final ficando apenas text_field_tag. %>
  <body>
    <%= nav_bar brand: "Loja", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Criar novo produto", new_produto_path %>
        <%= menu_item "Setores", setors_path %>
      <% end %>
      <%= form_tag busca_produto_path, method: :get, class:"navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :nome, @nome, class:"form-control" %>
        <%= button_to "Buscar", nil, class:"btn btn-default" %>
      </div>
    <% end %>
  <% end %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<%# #Vai buscar todas as messagens de erro e renderizar uma por uma. %>
<% @produto.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
    <%# #Vai renderizar as mensagens %>
        <%= msg %>
    </div>
<% end %>

<%= form_for @produto do |form| %>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= form.label :nome %>
                <%# Para código em Ruby, caso queira inserir uma classe de bootstrap, utilizar "class:"
                Em código HTML, utilizando "class=" %>
                <%= form.text_field :nome , class:"form-control"%>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= form.label :descricao%>
                <%= form.text_area :descricao, class:"form-control", rows:4%>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                <%= form.label :setor%>
                <%# #collection_select espera 4 parametros:
                #1 - Nome do campo que vai ser populado = :setor_id
                #2 - Nomes do campo que irão ser exibidos = @setor
                #3 - Nome do campo da tabela = :id
                #4 - Nome do campo que vai ser exibido = :nome %> 
                <%= form.collection_select :setor_id, @setores, :id, :nome, {}, class: "form-control"%>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :preco %>
                <%= form.number_field :preco, step:0.01, class:"form-control"%>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-1">
            <div class="form-group">
                <%= form.label :quantidade %>
                <%= form.number_field :quantidade, class:"form-control"%>
            </div>
        </div>
    </div>
    <%= form.submit texto_da_acao, class:"btn btn-primary"%>
<% end %>

app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.setor.nome %></td>
    <td><%= produto.preco %></td>
    <td><%= produto.quantidade %></td>
    <%# Utilizamos a propriedade "data" para perguntar se a pessoa tem certeza
    da ação de deletar o produto? %>
    <td><%= link_to "Editar", edit_produto_path(produto), class:"btn btn-default"%></td>
    <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger",
    data: {confirm:"Tem certeza que quer deletar #{produto.nome}?"}%></td>
</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Setor</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="2"></td>
        </tr>
    </thead>
    <tbody>
        <%= render @produtos %>
    </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Atualizar"} %>

app/views/produtos/index.html.erb
<%# #Se existir uma mensagem de erro/sucesso, será renderizada a mensagem de erro/sucesso. %>
<% if flash[:notice] %>
    <div class="alert alert-success">
    <%# #Vai renderizar a mensagem de sucesso. %>
        <%= flash[:notice] %>
    </div>
<% end %>

<div class="alert alert-info">
    <h4 class="alert-heading">Produtos adicionados recentemente</h4>
</div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <td>Nome</td>
                    <td>Descrição</td>
                    <td>Setor</td>
                    <td>Preço</td>
                    <td>Quantidade</td>
                    <td colspan="1"></td>
                </tr>
            </thead>
            <tbody>
                <%= render @produtos %>
            </tbody>
        </table>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Produto com desconto</h4>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <td>Nome</td>
                    <td>Descrição</td>
                    <td>Preço</td>
                    <td>Quantidade</td>
                    <td>Setor</td>
                </tr>
            </thead>
            <tbody>
                <%= render @produto_menor_preco%>
            </tbody>
        </table>
    </div>

app/views/produtos/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Criar"} %>

app/views/setors/_form.html.erb
<%= form_for(setor) do |f| %>
  <% if setor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setor.errors.count, "error") %> prohibited this setor from being saved:</h2>

      <ul>
      <% setor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setors/edit.html.erb
<h1>Editing Setor</h1>

<%= render 'form', setor: @setor %>

<%= link_to 'Visualizar', @setor, class:"btn btn-default" %> |
<%= link_to 'Voltar', setors_path, class:"btn btn-default" %>

app/views/setors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Setors</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @setors.each do |setor| %>
      <tr>
        <td><%= setor.nome %></td>
        <td><%= link_to 'Produtos', setor ,class:"btn btn-default"%></td>
        <td><%= link_to 'Editar', edit_setor_path(setor), class:"btn btn-default" %></td>
        <td><%= link_to 'Delete', setor, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar novo setor', new_setor_path, class:"btn btn-default" %>

app/views/setors/new.html.erb
<h1>New Setor</h1>

<%= render 'form', setor: @setor %>

<%= link_to 'Voltar', setors_path, class:"btn btn-default" %>

app/views/setors/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Setor</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="1"></td>
        </tr>
    </thead>
    <tbody>
        <%= render @produtos_por_setor %>
    </tbody>
</table>

<%= link_to 'Editar', edit_setor_path(@setor), class:"btn btn-default" %> |
<%= link_to 'Voltar', setors_path, class:"btn btn-default" %>